### ISSUE TITLE
merge this repo upstream once training finishes

### ISSUE THREAD

**Issue by martenson** [gvlproject/dagobah-training#4]
so we can merge the upstream into the bigger upstream

**Comment by bgruening** [comment]
Martin should we integrate this into the training_material repo?

**Comment by martenson** [comment]
@bgruening We can discuss if you want to, but our latest stance (me, @jmchilton, @natefoo, @blankenberg) on this was that admin documentation should live with the code. THe mentioned: please correct me if I am wrong.

**Comment by bgruening** [comment]
@martenson but this repo here does not live with the code? Sorry, don't get it.

**Comment by martenson** [comment]
@bgruening I meant "live with the code" as in "live with the Galaxy main codebase". I.e.: https://docs.galaxyproject.org/en/master/admin/index.html

**Comment by jmchilton** [comment]
We frequently make changes to wheels or scripts or settings that would affect admin training - I do think this is particularly tried to the Galaxy code and target version and so I would like to see it live in galaxyproject/galaxy. I wouldn't be sad to see it end up in training_material though - I'd just have a small preference for docs.galaxyproject.org if possible. If we can find a way to put training_material best practice training_material for a couple select topics into the core project - that would be great also.

I would also argue for a do-ocractic approach too though - if someone wants to take this material and put it in training_material and keep it up to date and would prefer that to galaxy core and no one steps up to put it into galaxy core that person should get to decide where it belongs I guess.

**Comment by martenson** [comment]
> if someone wants to take this material and put it in training_material and keep it up to date

Given the scope of administration topics in Galaxy this is no one-man-feat. We need to coordinate.

**Comment by jmchilton** [comment]
>  no one-man-feat

Well @bgruening is hardly just "one man" - anyway I just meant to convey that my opinion that this should be in core shouldn't really prevent it from landing up in training_material if I am not going to do the work to get it there. "Coordination" shouldn't be someone on devteam telling a community member where to put their work without getting skin in the game.

One thing I do need to do if get the "Galaxy Architecture" content both in the docs and in a best-practice ready to go training material-like module - so that is where I am coming from - I think admin topics are similar in focus and audience and so that is where my biases are coming from.

**Comment by martenson** [comment]
> "Coordination" shouldn't be someone on devteam telling a community member where to put their work without getting skin in the game.

I am talking about dagobah, where I have skin (is that the phrasing?).

**Comment by jmchilton** [comment]
I was not referring to you @martenson - I was referring to me. I chimed in to agree with your suggestion - just saying I don't have a ton of standing to do so - just a desire to see things move in this direction.

**Comment by natefoo** [comment]
Let's at least create branches for each "course" version so that attendees at each course can see the material as it was when they attended.

Some things that have become clear since doing the trainings:

- Because each step is additive, it's not trivial to do one exercise without doing all the ones before it
- It's also not trivial for future courses to rearrange sessions or leave sessions out because of the previous issue
- Adapting the training for each new session is a real pain if you are trying to make "cut-n-paste-able" materials since the method of accessing the training instance (user, pass, hostnames, etc.) will be different for each "course"

One solution to all of these problems would be building a set of Docker images, one for each session, that pre-incorporated relevant steps from other sessions. The downside is that in this case, users wouldn't end up with a "final" instance they could "take home" that included all of their cumulative work for the course. Also systemd doesn't work in Docker.

**Comment by hexylena** [comment]
We've solved all the issues and now it's in training materials, so I guess we can close this :)
